# Muestreo y Distribuciones en el Muestreo

## Ejercicio 1 
<!-- [W_M 7.11]  -->

Un guardabosque, que estudia los efectos de la fertilización en ciertos bosques de pinos en el sureste, está interesado en estimar el promedio de área de la base de los pinos. Al estudiar áreas basales de pinos similares durante muchos años, descubrió que estas mediciones (en pulgadas cuadradas) están distribuidas normalmente con desviación estándar aproximaa de 4 pulgadas cuadradas. 

Encuentre la probabilidad de que la media muestral se encuentre a no más de 2 pulgadas cuadradas de la media poblacional si se muestrean $n=9$ árboles

## Ejercicio 2 
<!-- [W_M 7.12-16] -->

Suponga que al guardabosque del 1 le gustaría que la media muestral estuviera a no más de 1 pulgada cuadrada de la media poblacional, con probabilidad 90%. ¿Cuántos árboles debe medir para asegurar este grado de precisión?

## Ejercicio 3 
<!-- [W_M 7.13] -->

La Agencia de Protección AMbiental  se ocupa del problema de establecer criterios para las cantidades de sustancias químicas tóxicas permitidas en lagos y ríos de agua dulce. 

Una medida común de toxicidad para cualquier contaminante es la concentración de éste que mataría a la mitad de la especie de prueba en un tiempo determinado (por lo general 96 horas para especies de peces).

Esta medida se denomina CL50 (concentración letal que mata 50% de la especie de prueba). En muchos estudios, los valores contenidos en el logaritmo natural de mediciones del CL50 están distribuidos normalmente y, en consecuencia, el análisis está basado en datos del $\ln(CL50)$.

Estudios de los efectos del cobre en cierta especie de peces (por ejemplo la especie A) muestran que la varianza de mediciones de $\ln(CL50)$ es alrededor de 0.4 con mediciones de concentración en miligramos por litro.

Si han de completarse $n=10$ estudios sobre el CL50 para cobre, encuentre la probabilidad de que la media muestral de $\ln(CL50)$ difiera de la verdadera media poblacional en no más de 0.5.

## Ejercicio 5 
<!-- [W_M 7.15] -->

Si en el Ejercicio anterior deseamos que la media muestral difiera de la media poblacional en no más de 0.5 con probabilidad .95 , ¿cuántas pruebas deben realizarse?


## Ejercicio 6

Suponga que $X_{1}, X_{2}, \ldots, X_{m}$ y $Y_{1}, Y_{2}, \ldots, Y_{n}$ son muestras aleatorias independientes, con las variables $X_{i}$ distribuidas normalmente con media $\mu_{1} \mathrm{y}$ varianza $\sigma_{1}^{2} \mathrm{y}$ las variables $Y_{i}$ distribuidas normalmente con media $\mu_{2}$ y varianza $\sigma_{2}^{2}$. La diferencia entre las medias muestrales, $\bar{X}-\bar{Y}$, es entonces una combinación lineal de $m+n$ variables aleatorias distribuidas normalmente y, por el las propiedades de las distribuciones normales, tiene una distribución normal.

a. Encuentre $E(\bar{X}-\bar{Y})$.
b. Encuentre $V(\bar{X}-\bar{Y})$.
c. Suponga que $\sigma_{1}^{2}=2, \sigma_{2}^{2}=2.5$ y $m=n$. Encuentre los tamaños muestrales para que $(\bar{X}-\bar{Y})$ se encuentre a no más de 1 unidad de $\left(\mu_{1}-\mu_{2}\right)$ con probabilidad .95 .

## Ejercicio 7

Refiriéndose al Ejercicio 3, suponga que los efectos del cobre en una segunda especie (por ejemplo la especie B) de peces muestran la varianza de mediciones de $\ln(CL50)$ que son de .8 . 

Si las medias poblacionales del $\ln(CL50)$ para las dos especies son iguales, encuentre la probabilidad de que, con muestras aleatorias de diez mediciones de cada especie, la media muestral para la especie A sea mayor a la media muestral para la especie B en al menos 1 unidad.

## Ejercicio 8

La acidez de los suelos se mide mediante una cantidad llamada pH , que varía de 0 (acidez alta) a 14 (alcalinidad alta). Un edafólogo desea calcular el promedio de pH para un campo de grandes dimensiones al seleccionar aleatoriamente $n$ muestras de núcleos y medir el pH de cada muestra. 

Aun cuando la desviación estándar poblacional de mediciones de pH no se conoce, la experiencia del pasado indica que casi todos los suelos tienen un valor de pH de entre 5 y 8. Si el científico selecciona $n=40$ muestras, encuentre la probabilidad aproximada de que la media muestral de las 40 mediciones de pH esté a .2 unidades del verdadero promedio de pH para el campo. 
<!-- [Sugerencia: vea el Ejercicio 1.17.] -->


## Ejercicio 9 

<!-- [W-M 7.68] -->

En 1998, el estado de Florida resultó afectado por cuatro huracanes de gran intensidad. En 2005 un estudio indicó que en 2004, $48 \%$ de las familias en Florida no tenían planes para escapar de un huracán que se aproximaba. 

Suponga que una muestra aleatoria reciente de 50 familias se seleccionó en Gainesville y que los miembros de 29 de las familias indicaron que tenían un plan de escape en caso de huracán.

a. Si los porcentajes estatales de 2004 todavía fueran válidos para las familias recientes de Gainesville. Use R para calcular las probabilidades siguiendo una distribución binomial y también una aproximación Normal a la Binomial para determinar los valores exacto y aproximado de la probabilidad que 29 o más de las familias muestreadas tengan un plan de escape para el huracán.

b. ¿La aproximación normal es cercana a la probabilidad binomial exacta? Explique por qué.

## Ejercicio 10

Para verificar la abundancia relativa de cierta especie de peces en dos lagos, se toman $n=50$ observaciones relacionadas con los resultados de la captura en cada uno de los lagos. Para cada observación, el experimentador sólo registra si la especie deseada estaba presente en la trampa. 

La experiencia del pasado ha demostrado que esta especie aparece en trampas del lago A aproximadamente $10 \%$ del tiempo y en trampas del lago B, alrededor de $20 \%$ del tiempo. Use estos resultados para aproximar la probabilidad de que la diferencia entre las proporciones muestrales sea de no más de .1 de la diferencia entre las proporciones reales.
