# Aplicaciones de los contrastes de hipótesis

## Elección del tipo de test

Estos ejercicios representan situaciones típicas en los que se puede utilizar un contraste de hipótesis para decidir entre dos hipótesis relativas a un problema.

En una situación real debemos (solemos) empezar con una visualización de los datos y, eventualmente, cuando procede (en variables cuantitativas) un test de normalidad que nos sirve para decidir que tipo de contraste utilizar.

Estos ejercicios se han adaptado del excelente libro de Baron y otros (Bioestadística) de la Universidad de Málaga, pero por su naturaleza más académica, no vienen acompañados de conjuntos de datos mínimamente grandes, como para poder hacer dichas visualizaciones y pruebas de normalidad.

En consecuencia, la "decisión" sobre si utilizar un test paramétrico o no paramétrico puede ser más difícil de tomar.

A título de pista podemos decir que los ejercicios 1 al 9 están tomados del capítulo de pruebas paramétricas, del 10 al 13 del capítulo de pruebas de la ji cuadrado y del 14 al 18 del capítulo de pruebas no paramétricas de dicho documento.

Sin embargo, y con el fin de motivar un trabajo reflexivo, os animo a justificar en cada caso porque decidís aplicar el tests que aplicáis. Y, de hecho, cuando sea posible, os animo también a aplicar tanto la versión paramétrica como la no paramétrica de un test y valorar, aparte de cual es el adecuado, si os llevan o no  ala misma conclusión.

## Procedimiento del test (Neymann-Pearson)

Recordad que la aplicación de un contraste no consiste en escribir un código de R, mirar un p-valor y decidir si rechazamos o no la hipótesis.

Aunque no es bueno adherirse a un esquema rígido si que resulta útil tener una mínima pauta que podemos considerar común a la mayoría de los problemas en los que aplicamos el contraste de hipótesis.

Esta pauta puede describirse de la forma siguiente:

_I: **ANTES DE OBTENER LOS DATOS** deberíamos:_

0. Definir el modelo probabilístico sobre el que realizaremos el contraste

1. Definir el tamaño del efecto a detectar en la población (en estos ejercicios suele ser cero)

2. Reformular la pregunta de investigación en términos de las hipótesis nula y alternativa ($H_0$ y $H_1$)

3. Elegir el nivel de significación $\alpha$ (e, idealmente la potencia $1-\beta$) con los que controlaremos el error de tipo I y de tipo II ($\beta$) respectivamente. Habitualmente tan sólo podemos prefijar $\alpha$

4. Escoger el estadístico de test adecuado al problema, el modelo y las hipótesis. Idealmente desearemos que sea un test _óptimo_

5. Calcular el tamaño de la muestra necesario para alcanzar la potencia deseada.

6. Obtener el valor crítico $t_{\alpha}$ asociado al estadístico de test seleccionado. Esto equivale a definir la región crítica del test.

_II: Proceder a recoger los datos_

_III: **UNA VEZ SE HAN OBTENIDO LOS DATOS**_

7. Calcular el valor del estadístico de test en la muestra, $t^{obs}$

8. Decidir si, a la vista de la comparación entre $t_{\alpha}$ y $t^{obs}$  nos inclinamos por la hipótesis nula o la alternativa.

9. Interpretar la decisión en términos de la hipótesis científica que ha generado el problema. Diferenciar cuando sea posible si hay significación estadística, clínica/biológica o ambas


En la práctica, y en los ejercicios que siguen, podemos encontrarnos con los datos recogidos y desear llevar a cabo el contraste.

En este caso, omitiremos el cálculo del tamaño muestral y la potencia.

Esta lista no es una plantilla para resolver cualquier problema de contraste de hipótesis, pero sí que debe ayudarnos a ver que un test no es tan solo un cálculo y una decisión basada en un p-valor sino un proceso de toma de decisión que, para que tenga sentido  debe de realizarse teniendo en cuenta los elementos que se han descrito.

## ¿Y que hay del p-valor? (Fisher)

Obsérvese que el procedimiento descrito no ha hecho referencia al p-valor, [concepto particularmente discutido en la estadística actual](https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf).

El p-valor, de hecho, no forma parte del esquema presentado, basado en la teoría de contraste de hipótesis de Neymann-Pearson sino de la teoría de las pruebas de significación estadística introducida por R.A. Fisher.

Dichas pruebas de significación iban principalmente encaminadas a decidir si se rechazaba o no una hipótesis (no había hipótesis alternativa) e, informalmente los pasos a realizar eran:

1. Seleccionar un estadístico de test que mida adecuadamente la discrepancia entre la hipótesis y las observaciones.

2. Construir la hipótesis nula

3. Calcular la probabilidad teórica del resultado observado $t^{obs}$, bajo la hipótesis nula, es decir el p-valor.

4. Decidir sobre la significación de los resultados, si la probabilidad de los mismos _bajo $H_0$_ era "pequeña" (Fisher no imponía puntos de corte). Es decir rechazar la hipótesis nula si el p-valor es pequeño.

5. Interpretar los resultados.

## Combinando ambas aproximaciones

Fisher y Neymann-Pearson debatieron duramente, hace casi un siglo, sobre cual de las dos aproximaciones era la adecuada.

Sin entrar en la polémica entre ambas, el hecho es que con el tiempo, muchos autores tendieron a fundir (y a confundir!) ambas aproximaciones, lo que llevó a combinar las hipótesis nula y alternativa de Neymann-pearson con el p-valor de Fisher.

En la actualidad, en la que la mayoría de los cálculos se llevan a cabo con ordenador, es inmediato, tras calcular el valor del estadístico de test, obtener el p-valor de la prueba por lo que la decisión sobre si se acepta la hipótesis nula o la alternativa se realiza a menudo comparando el p-valor con la probabilidad de error de tipo I ($\alpha$) en vez de comparar el valor observado del estadístico de test ($t^{obs}$) con el valor crítico ($t_\alpha$). En la práctica, _esta sustitución puede considerarse adecuada si no va más allá de cambiar un criterio de decisión por otro._

## Referencias

- [Fisher, Neyman-Pearson or NHST? A tutorial for teaching data testing](https://pmc.ncbi.nlm.nih.gov/articles/PMC4347431/)


# Ejercicios

## Ejercicio 1 
<!-- Barón 9.1 -->

El calcio se presenta normalmente en la sangre de los mamíferos en concentraciones de alrededor de 6 mg por cada 100 ml del total de sangre. La desviación típica normal de ésta variable es 1 mg de calcio por cada 100 ml del volumen total de sangre. Una variabilidad mayor a ésta puede ocasionar graves trastornos en la coagulación de la sangre. Una serie de nueve pruebas sobre un paciente revelaron una media muestral de $6,2 \mathrm{mg}$ de calcio por 100 ml del volumen total de sangre, y una desviación típica muestral de 2 mg de calcio por cada 100 ml de sangre. ¿Hay alguna evidencia, para un nivel $\alpha=0,05$, de que el nivel medio de calcio para este paciente sea más alto del normal?


## Ejercicio 2
<!-- Barón 9.4 -->

Las guías médicas recomiendan realizar una campaña de educación e higiene dental  si el porcentaje de niños con dientes cariados es superior al $15 \%$. 
En una población con 12.637 niños, ¿debe hacerse la campaña si, de 387 de ellos, 70 tenían algún diente cariado?


## Ejercicio 3
<!-- Barón 9.10 -->

Muchos autores afirman que los pacientes con depresión tienen una función cortical por debajo de lo normal debido a un riego sanguíneo cerebral por debajo de lo normal. A dos muestras de individuos, unos con depresión y otros normales, se les midió un índice que indica el flujo sanguíneo en la materia gris (dado en $\mathrm{mg} /(100 \mathrm{~g} / \mathrm{min})$) obteniéndose:

$$
\begin{array}{l|ccc}
\text { Depresivos } & n_{1}=19 & \bar{x}_{1}=47 & \hat{\mathcal{S}}_{1}=7^{\prime} 8 \\
\hline \text { Normales } & n_{2}=22 & \bar{x}_{2}=53^{\prime} 8 & \hat{\mathcal{S}}_{2}=6^{\prime} 1
\end{array}
$$

¿Hay evidencia significativa a favor de la afirmación de los autores?


## Ejercicio 4 
<!-- Barón 9.11 -->

La prueba de la d-xilosa permite la diferenciación entre una esteatorrea originada por una mala absorción intestinal y la debida a una insuficiencia pancreática, de modo que cifras inferiores a 4 grs. de d-xilosa, indican una mala absorción intestinal. Se realiza dicha prueba a 10 individuos, obteniéndose una media de 3,5 grs. y una desviación típica de 0,5 grs. ¿Se puede decir que esos pacientes padecen una mala absorción intestinal?

## Ejercicio 5
<!-- Barón 9.13 -->

La tabla siguiente muestra los efectos de un placebo y de la hidroclorotiacida sobre la presión sanguínea sistólica de 11 pacientes.

| Placebo | 211 | 210 | 210 | 203 | 196 | 190 | 191 | 177 | 173 | 170 | 163 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| H-cloro | 181 | 172 | 196 | 191 | 167 | 161 | 178 | 160 | 149 | 119 | 156 |

Según estos datos experimentales, ¿podemos afirmar que existe diferencia en la presión sistólica media durante la utilización de estos dos fármacos?


## Ejercicio 6 
<!-- Barón 9.15 -->

De un estudio sobre la incidencia de la hipertensión en la provincia de Málaga, se sabe que en la zona rural el porcentaje de hipertensos es del $27,7 \%$. Tras una encuesta a 400 personas de una zona urbana, se obtuvo un $24 \%$ de hipertensos.

1. ¿Se puede decir que el porcentaje de hipertensos en la zona urbana es distinto que en la zona rural?
2. ¿Es menor el porcentaje de hipertensos en la zona urbana que en la zona rural?


## Ejercicio 7
<!-- Barón 9.17 -->

Se desea comparar la actividad motora espontánea de un grupo de 25 ratas control y otro de 36 ratas desnutridas. Se midió el número de veces que pasaban delante de una célula fotoeléctrica durante 24 horas. Los datos obtenidos fueron los siguientes:

$$
\begin{array}{l|ccc}
\text { Ratas de control } & n_{1}=25 & \bar{x}_{1}=869,8 & \mathcal{S}_{1}=106,7 \\
\hline \text { Ratas desnutridas } & n_{2}=36 & \bar{x}_{2}=465 & \mathcal{S}_{2}=153,7
\end{array}
$$

¿Se observan diferencias significativas entre el grupo control y el grupo desnutrido?

## Ejercicio 8
<!-- Barón 9.18 -->

Se pretende comprobar la hipótesis expuesta en algunos trabajos de investigación acerca de que la presencia del antígeno AG-4 está relacionada con un desenlace fatal. Con éste fin, se hizo una revisión sobre las historias clínicas de 21 mujeres muertas por carcinoma de cuello uterino, observando que 6 de ellas presentaban el citado antígeno. Por otro lado y con fines de comparación se tomó otra muestra de 42 personas, con edades similares a las del grupo anterior y que reaccionaron bien al tratamiento del carcinoma de cuello uterino, en 28 de las cuales se observó la presencia del citado antígeno. ¿Puede pues afirmarse que la presencia del antígeno se relaciona con una efectividad del tratamiento?


## Ejercicio 9
<!-- Barón 9.21 -->

Para comprobar si la tolerancia a la glucosa en sujetos sanos tiende a decrecer con la edad se realizó un test oral de glucosa a dos muestras de pacientes sanos, unos jóvenes y otros adultos. El test consistió en medir el nivel de glucosa en sangre en el momento de la ingestión (nivel basal) de 100 grs. de glucosa y a los 60 minutos de la toma. Los resultados fueron los siguientes:

Jóvenes: | Basal | 81 | 89 | 80 | 75 | 74 | 97 | 76 | 89 | 83 | 77 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| 60 minutos | 136 | 150 | 149 | 141 | 138 | 154 | 141 | 155 | 145 | 147 |

Adultos: | Basal | 98 | 94 | 93 | 88 | 79 | 90 | 86 | 89 | 81 | 90 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| 60 minutos | 196 | 190 | 191 | 189 | 159 | 185 | 182 | 190 | 170 | 197 |

1. ¿Se detecta una variación significativa del nivel de glucosa en sangre en cada grupo?
2. ¿Es mayor la concentración de glucosa en sangre a los 60 minutos, en adultos que en jóvenes?
3. El contenido basal de glucosa en sangre, ¿es menor en jóvenes que en adultos?
4. ¿Se detecta a los 60 minutos una variación del nivel de glucosa en sangre diferente de los adultos, en los jóvenes?


## Ejercicio 10 
<!-- Barón 10.1 -->

Ante la sospecha de que el hábito de fumar de una embarazada puede influir en el peso de su hijo al nacer, se tomaron dos muestras, una de fumadoras y otra de no fumadoras, y se clasificó a sus hijos en tres categorías en función de su peso en relación con los percentiles $\mathcal{P}_{10}$ y $\mathcal{P}_{90}$ de la población. El resultado se expresa en la tabla siguiente:

| Peso del niño |  |  |  |
| :---: | :---: | :---: | :---: |
| ¿Madre fumadora? | Menor de $\mathcal{P}_{10}$ | Entre $\mathcal{P}_{10}$ y $\mathcal{P}_{90}$ | Mayor de $\mathcal{P}_{90}$ |
|  | 117 | 529 | 19 |
|  | 124 | 1147 | 117 |
|  |  |  |  |

¿Hay una evidencia significativa a favor de la sospecha a la vista de los resultados de la muestra?


## Ejercicio 11
<!-- Barón 10.3 -->

Varios libros de Medicina Interna recomiendan al médico la palpación de la arteria radial con el fin de evaluar el estado de la pared arterial. Se tomaron 215 pacientes y se les clasificó según la palpabilidad de dicha arteria (grados 0,1 y 2 para no palpable, palpable y muy palpable o dura, respectivamente) y según una puntuación de 0 a 4 en orden creciente de degeneración arterial (evaluada tras la muerte del paciente y su análisis anatomo-patológico). Los datos son los de la tabla siguiente:

|  |  | Palpabilidad |  |  |
| :---: | :---: | :---: | :---: | :---: |
| Degeneración | $\mathbf{0}$ | $\mathbf{1}$ | $\mathbf{2}$ |  |
| $\mathbf{0}$ | 20 | 5 | 5 |  |
| $\mathbf{1}$ | 60 | 20 | 10 |  |
| $\mathbf{2}$ | 45 | 15 | 15 |  |
| $\mathbf{3}$ | 10 | 5 | 5 |  |
|  |  |  |  |  |

¿Existe relación entre el grado de palpabilidad y el análisis anatomopatológico?



## Ejercicio 12 
<!-- Barón 10.3 -->

Con el fin de conocer si un cierto tipo de bacterias se distribuyen al azar en un determinado cultivo o si, por el contrario, lo hacen con algún tipo de preferencia (el centro, los extremos, etc...), se divide un cultivo en 576 áreas iguales y se cuenta el número de bacterias en cada área. Los resultados son los siguientes:

| $n^{o}$ de bacterias | 0 | 1 | 2 | 3 | 4 | $\geq 5$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
|  | $n^{o}$ de áreas | 229 | 211 | 93 | 35 | 7 |

¿Obedecen los datos a una distribución de Poisson?


## Ejercicio 13 
<!-- Barón 10.9 -->

Deseamos conocer, si las distribuciones atendiendo al grupo sanguíneo, en tres muestras referidas atendiendo al tipo de tensión arterial, se distribuyen de igual manera. Para lo cual, se reunió una muestra de 1500 sujetos a los que se les determinó su grupo sanguíneo y se les tomó la tensión arterial, clasificándose ésta en baja, normal, y alta. Obteniéndose los siguientes resultados:

|  |  | Grupo sanguíneo |  |  |  |  |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Tensión arterial | A | B | AB | O | Total |  |
| Baja | 28 | 9 | 7 | 31 | 75 |  |
| Normal | 543 | 211 | 90 | 476 | 1.320 |  |
| Alta | 44 | 22 | 8 | 31 | 105 |  |
| Total | 615 | 242 | 105 | 538 | 1.500 |  |
|  |  |  |  |  |  |  |


## Ejercicio 14
<!-- Barón 12.3 -->

Se realiza un estudio para determinar los efectos de poner fin a un bloqueo renal en pacientes cuya función renal está deteriorada a causa de una metástasis maligna avanzada de causa no urológica. Se mide la tensión arterial de cada paciente antes y después de la operación. Se obtienen los siguientes resultados:

> Tensión arterial

| Antes | 150 | 132 | 130 | 116 | 107 | 100 | 101 | 96 | 90 | 78 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Después | 90 | 102 | 80 | 82 | 90 | 94 | 84 | 93 | 89 | $8 ? ? ? ? ?$ |

¿Se puede concluir que la intervención quirúrgica tiende a disminuir la tensión arterial?


## Ejercicio 15
<!-- Barón 12.3 -->

Se ensayaron dos tratamientos antirreumáticos administrados al azar, sobre dos grupos de 10 pacientes, con referencia a una escala convencional (a mayor puntuación, mayor eficacia), valorada después del tratamiento. Los resultados fueron:

Nivel de eficacia del tratamiento

| Tratamiento primero | 12 | 15 | 21 | 17 | 38 | 42 | 10 | 23 | 35 | 28 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Tratamiento segundo | 21 | 18 | 25 | 14 | 52 | 65 | 40 | 43 | 35 | 42 |

Decidir si existe diferencia entre los tratamientos.


## Ejercicio 16
<!-- Barón 12.9 -->

Los siguientes datos nos dan el peso de comida (en Kg.) consumidos por adulto y día en diferentes momentos en un año. Usar un contraste no paramétrico para comprobar si el consumo de comida es el mismo en los 4 meses considerados.

| Febrero | Mayo | Agosto | Noviembre |
| :---: | :---: | :---: | :---: |
| $4^{\prime} 7$ | $4^{\prime} 7$ | $4^{\prime} 8$ | $4^{\prime} 9$ |
| $4^{\prime} 9$ | $4^{\prime} 4$ | $4^{\prime} 7$ | $5^{\prime} 2$ |
| $5^{\prime} 0$ | $4^{\prime} 3$ | $4^{\prime} 6$ | $5^{\prime} 4$ |
| $4^{\prime} 8$ | $4^{\prime} 4$ | $4^{\prime} 4$ | $5^{\prime} 1$ |
| $4^{\prime} 7$ | $4^{\prime} 1$ | $4^{\prime} 7$ | $5^{\prime} 6$ |

## Ejercicio 17
<!-- Barón 12.10 -->

Se hizo un estudio neurofisiológico sobre la conducción motora tibial posterior en dos grupos de pacientes embarazadas con las siguientes determinaciones:

Conducción motora tibial posterior

| Primer grupo | 51 | 40 | 41 | 53 | 48 | 50 | 45 | 58 | 45 | 44 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Segundo grupo | 58 | 43 | 40 | 45 | 41 | 42 | 44 | 52 | 56 | 48 |

Comprobar la igualdad o no de ambas muestras.

## Ejercicio 18
<!-- Barón 12.11 -->

En un experimento diseñado para estimar los efectos de la inhalación prolongada de óxido de cadmio, 15 animales de laboratorio sirvieron de sujetos para el experimento, mientras que 10 animales similares sirvieron de controles. La variable de interés fue el nivel de hemoglobina después del experimento. Se desea saber si puede concluirse que la inhalación prolongada de óxido de cadmio disminuye el nivel de hemoglobina según los siguientes datos que presentamos:

Nivel de hemoglobina

| Expuestos | $14^{\prime} 4$ | $14^{\prime} 2$ | $13^{\prime} 8$ | $16^{\prime} 5$ | $14^{\prime} 1$ | $16^{\prime} 6$ | $15^{\prime} 9$ | $15^{\prime} 6$ | $14^{\prime} 1$ | $15^{\prime} 3$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
|  | $15^{\prime} 7$ | $16^{\prime} 7$ | $13^{\prime} 7$ | $15^{\prime} 3$ | $14^{\prime} 0$ |  |  |  |  |  |
| No expuestos | $17^{\prime} 4$ | $16^{\prime} 2$ | $17^{\prime} 1$ | $17^{\prime} 5$ | $15^{\prime} 0$ | $16^{\prime} 0$ | $16^{\prime} 9$ | $15^{\prime} 0$ | $16^{\prime} 3$ | $16^{\prime} 8$ |


## Ejercicio 19
<!-- Barón 12.12 -->

A 11 ratas tratadas crónicamente con alcohol se les midió la presión sanguínea sistólica antes y después de 30 minutos de administrarles a todas ellas una cantidad fija de etanol, obteniéndose los datos siguientes:

Presión sanguínea sistólica

| Antes | 126 | 120 | 124 | 122 | 130 | 129 | 114 | 116 | 119 | 112 | 118 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Después | 119 | 116 | 117 | 122 | 127 | 122 | 110 | 120 | 112 | 110 | 111 |

¿Hay un descenso significativo de la presión sanguínea sistólica tras la ingestión de etanol?


